/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sellable positions this partner/advertiser could buy
         * @description Only advertiser-owned slots. Positions the caller can't buy (blacklisted,
         *     excluded by whitelist-only, or reserved to another advertiser) are omitted,
         *     never returned as errors.
         */
        get: operations["listInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/{positionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One position in full */
        get: operations["getPosition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/{positionId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status per play window across a date range */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Projected assumed views for a position set and targeting */
        post: operations["forecast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/targeting/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The shared targeting variables this partner may use
         * @description Only variables enabled for the calling DSP. Values are never returned.
         */
        get: operations["listTargetingAttributes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a campaign (content package) — baseline plus targeted versions
         * @description Targeting rules are validated against the variables permitted for the
         *     calling DSP and stored in the existing campaign targeting structure.
         *     Evaluation and playback are the existing platform's.
         */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload creative for the baseline or a targeted version; runs automated checks */
        post: operations["uploadAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit for retailer approval (or auto-approve if the advertiser doesn't require it) */
        post: operations["submitCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval status and rejection reason */
        get: operations["getCampaignStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserve (named advertiser) or bid (CPM) for a play window
         * @description Approved and activated campaigns only, while the window's auction is open (from 7 days before the window until its auction runs, 6 hours before). Pre-auction checks apply (floor, lists, categories, approval, activation).
         */
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{reservationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One reservation or bid, with its outcome */
        get: operations["getReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExchange"];
        /** Save changes (whole page) */
        put: operations["saveExchange"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/advertiser-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdvertiserSettings"];
        /** Save changes — pricing and list management */
        put: operations["saveAdvertiserSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/available-inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read-only table of advertiser-owned slots (no advertisers column) */
        get: operations["listAvailableInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/targeting-variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSharedTargetingVariables"];
        /** Save changes — which DSPs may target each variable */
        put: operations["saveVariableAccess"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPartners"];
        put?: never;
        /** Add a DSP (starts in Test, adopts company lists) */
        post: operations["addPartner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/partners/{partnerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPartner"];
        /**
         * Save changes — credentials, bidder, mode, own lists
         * @description Whole-page save. Secret credential fields are write-only: send a new value
         *     to replace, omit to keep. mode "live" is rejected unless connected and the
         *     bidder integration is complete.
         */
        put: operations["savePartner"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/partners/{partnerId}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect or re-test with the saved credentials; pulls seats/advertisers */
        post: operations["connectPartner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/partners/{partnerId}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disconnectPartner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/advertisers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every advertiser across all DSPs (admin users only) */
        get: operations["listAdvertisers"];
        /** Save changes — approval required and floor multiplier per advertiser */
        put: operations["saveAdvertisers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaigns by approval status, with counts (for the campaign table filter) */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/campaigns/{campaignId}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval state, check results and audit trail (review panel) */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/campaigns/{campaignId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/campaigns/{campaignId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/display-types/{displayTypeId}/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save slot ownership and venue metadata (phExtensions only)
         * @description Existing display type fields keep using the existing display type API.
         */
        put: operations["saveDisplayTypeExtensions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/display-types/{displayTypeId}/delete-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Can this display type be deleted? Lists assigned displays if not. */
        get: operations["checkDisplayTypeDelete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/display-types/{displayTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete; 409 with the assigned displays if any remain */
        delete: operations["deleteDisplayType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/playlists/{playlistId}/delete-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Can this playlist be deleted? Lists display type / zone assignments if not. */
        get: operations["checkPlaylistDelete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/playlists/{playlistId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete; 409 with the assignments if it is a default or zone playlist */
        delete: operations["deletePlaylist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/display-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDisplayTypes"];
        put?: never;
        /** New display type (also creates its auto-created playlist) */
        post: operations["createDisplayType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/display-types/{displayTypeId}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDisplayType"];
        /** Save changes — the existing display type fields (phExtensions are saved via /extensions) */
        put: operations["saveDisplayType"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playlists with their display type and zone assignments */
        get: operations["listPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/playlists/{playlistId}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit a playlist — name only (assignments are made on the display type form, spec §2) */
        put: operations["savePlaylist"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaigns for the stand-in POC campaign table (existing campaign list) */
        get: operations["listCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/campaigns/{campaignId}/activation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Switch a campaign Active / Inactive (existing activation toggle); approved campaigns only */
        put: operations["setCampaignActivation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current stand-in user and role (from the POC_ROLE env var; no switcher, no cookie) */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sellers.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** IAB sellers.json for the seller of record (served at https://[domain]/sellers.json) */
        get: operations["getSellersJson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "validation_failed" | "variable_not_permitted" | "checks_failed" | "not_approved" | "below_floor" | "advertiser_blocked" | "category_blocked" | "not_on_whitelist" | "conflict" | "has_dependents" | "unauthorised" | "forbidden" | "not_found";
                message: string;
                details?: {
                    field?: string;
                    variable?: string;
                    reason?: string;
                }[];
            };
        };
        /** @enum {string} */
        WindowStatus: "available" | "reserved" | "sold" | "unavailable";
        PlayWindow: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            status: components["schemas"]["WindowStatus"];
            assumedViews: number;
        };
        Position: {
            positionId: string;
            displayTypeId: string;
            displayTypeName: string;
            slot: number;
            slotLabel: string;
            zone?: string | null;
            storeCount: number;
            displayCount: number;
            screen: {
                width: number;
                height: number;
                /** @enum {string} */
                orientation: "landscape" | "portrait";
                slotDurationSec: number;
                loopLengthSec: number;
                /** @description 1 / maximumCampaignsPlayedInRotation */
                shareOfVoice: number;
                openOohVenueType?: string;
            };
            /** @enum {string} */
            assignment: "rtb" | "whitelist_only" | "reserved";
            assumedViewsPerWindow?: number;
            pricing: components["schemas"]["Pricing"];
        };
        Pricing: {
            currency: string;
            floorCpm: number;
            effectiveFloorCpm: {
                localised: number;
                personalised: number;
                interactive: number;
                personalisedInteractive: number;
            };
        };
        TargetingAttribute: {
            /** @example store.fixed_segments */
            key: string;
            /** @enum {string} */
            source: "store" | "visitor";
            label: string;
            /** @enum {string} */
            group: "localisation" | "personalisation";
            operators: string[];
        };
        Condition: {
            source: string;
            variable: string;
            /** @enum {string} */
            op: "include" | "match_exactly" | "exclude_or" | "exclude_and" | "equal" | "not_equal" | "greater_than" | "less_than" | "greater_than_or_equal" | "less_than_or_equal";
            values: string[];
        };
        /** @description AND groups of OR conditions (existing Targeting tab structure). */
        TargetingRules: components["schemas"]["Condition"][][];
        /** @enum {string} */
        PricingType: "baseline" | "localised" | "personalised" | "interactive";
        CampaignCreate: {
            advertiserId: string;
            name: string;
            displayTypeId?: string;
            baseline: {
                pricingType: components["schemas"]["PricingType"];
            };
            targeted?: {
                id: string;
                priority: number;
                pricingType: components["schemas"]["PricingType"];
                rules: components["schemas"]["TargetingRules"];
            }[];
        };
        /** @enum {string} */
        ApprovalStatus: "draft" | "awaiting_approval" | "approved" | "rejected";
        Check: {
            /** @enum {string} */
            name: "file_type" | "file_size" | "bitrate" | "dimensions" | "aspect_ratio" | "duration" | "baseline_present" | "targeting_permitted";
            passed: boolean;
            detail?: string;
        };
        CampaignStatus: {
            campaignId: string;
            status: components["schemas"]["ApprovalStatus"];
            /** @enum {string|null} */
            mode?: "manual" | "auto" | null;
            reason?: string | null;
            assetVersion?: string | null;
        };
        ReservationCreate: {
            positionId: string;
            /** Format: date-time */
            windowStart: string;
            campaignId: string;
            advertiserId: string;
            /** @enum {string} */
            type: "reserve" | "bid";
            /** @description The CPM, in the company currency: the bid (type bid), or the reservation price agreed through the DSP (type reserve). Must clear the effective floor. A reservation is booked at this price. */
            bidCpm: number;
        };
        Reservation: {
            reservationId: string;
            /** @enum {string} */
            status: "pending" | "won" | "lost" | "reserved" | "rejected";
            clearingCpm?: number | null;
            currency?: string;
            reason?: string | null;
        };
        Exchange: components["schemas"]["ExchangeInput"] & {
            published: boolean;
            sellersJsonUrl?: string | null;
        };
        ExchangeInput: {
            organisation: string;
            domain: string;
            sellerId: string;
            /** Format: email */
            contactEmail: string;
        };
        AdvertiserSettingsInput: {
            /**
             * @description ISO 4217
             * @default AUD
             */
            currency: string;
            /** @default 100 */
            floorCpm: number;
            /** @default 1.5 */
            personalisedMultiplier: number;
            /** @default 3 */
            interactiveMultiplier: number;
            advertiserWhitelist: string[];
            advertiserBlacklist: string[];
            /** @description IAB categories */
            categoryWhitelist: string[];
            categoryBlacklist: string[];
        };
        AdvertiserSettings: components["schemas"]["AdvertiserSettingsInput"] & {
            /** @description Read-only. Per DSP, adopting the company lists or own lists. */
            whereTheseApply: {
                partnerId: string;
                name: string;
                adopting: boolean;
            }[];
        };
        AvailableInventoryRow: {
            displayTypeId: string;
            displayTypeName: string;
            touchPoint?: string;
            playlistName: string;
            slot: number;
            position: string;
            partnerName?: string | null;
        };
        VariableAccess: "all" | string[];
        SharedVariable: {
            key: string;
            label: string;
            /** @enum {string} */
            group: "localisation" | "personalisation";
            /** @description Tooltip text */
            exampleValues: string;
            access: components["schemas"]["VariableAccess"];
        };
        /** @enum {string} */
        Provider: "google_dv360" | "amazon_dsp" | "the_trade_desk";
        Partner: {
            id: string;
            provider: components["schemas"]["Provider"];
            name: string;
            /** @enum {string} */
            status: "draft" | "connected" | "error";
            /** @description Last connection result */
            lastSync?: string | null;
            /** @enum {string} */
            mode: "test" | "live";
            /** @description Non-secret fields in full; secret fields only as {set:true}. */
            credentials?: {
                [key: string]: unknown;
            };
            bidder?: {
                /** Format: uri */
                bidderEndpoint?: string;
                seatIds?: string[];
            };
            /** @description Shown at the top of the DSP page. */
            issues?: {
                /** @enum {string} */
                kind: "connection_error" | "missing_credentials" | "missing_bidder_fields";
                message: string;
                fields?: string[];
            }[];
            /** @description The DSP's seats and advertisers, pulled on connect (spec §8). Offered in the slot picker and as list suggestions. */
            seats?: {
                id: string;
                name: string;
            }[];
            listsLinked: boolean;
            /** @description Own lists */
            advertiserWhitelist?: string[];
            advertiserBlacklist?: string[];
        };
        PartnerInput: {
            /**
             * @description google_dv360 — partnerId, serviceAccountEmail, privateKeyJson (secret).
             *     amazon_dsp — region, lwaClientId, lwaClientSecret (secret), refreshToken (secret), profileId, entityId.
             *     the_trade_desk — supplySourceId, ttdPartnerId, apiToken (secret), region.
             */
            credentials?: {
                [key: string]: string;
            };
            bidder?: {
                /** Format: uri */
                bidderEndpoint?: string;
                seatIds?: string[];
            };
            /** @enum {string} */
            mode?: "test" | "live";
            /** @description false copies the company lists down; true discards own lists. */
            listsLinked?: boolean;
            advertiserWhitelist?: string[];
            advertiserBlacklist?: string[];
        };
        AdvertiserSetting: {
            /** @default true */
            approvalRequired: boolean;
            /** @default 1 */
            floorMultiplier: number;
        };
        Advertiser: components["schemas"]["AdvertiserSetting"] & {
            advertiserId: string;
            name: string;
            /** @description DSP names */
            via: string[];
            effectiveFloorCpm: number;
        };
        Approval: {
            campaignId: string;
            campaignName?: string;
            advertiserName?: string;
            partnerName?: string;
            status: components["schemas"]["ApprovalStatus"];
            /** @enum {string|null} */
            mode?: "manual" | "auto" | null;
            assetVersion: string;
            /** Format: date-time */
            submittedAt?: string | null;
            reviewedBy?: string | null;
            /** Format: date-time */
            reviewedAt?: string | null;
            reason?: string | null;
            checks?: components["schemas"]["Check"][];
            targetingSummary?: string;
            /** @description The baseline creative under review, for rendering on the target canvas. */
            creative?: {
                assetUrl: string;
                mimeType: string;
                width: number;
                height: number;
            } | null;
            /** @description The target display type's canvas. */
            canvas?: {
                width: number;
                height: number;
            } | null;
            audit?: {
                /** Format: date-time */
                at: string;
                /** @enum {string} */
                action: "submitted" | "auto_approved" | "approved" | "rejected" | "returned_for_review";
                by?: string | null;
                reason?: string | null;
                assetVersion?: string;
            }[];
        };
        DisplayTypeExtensions: {
            slots: {
                label: string;
                /** @enum {string} */
                owner: "internal" | "advertiser" | "retail";
                partnerId?: string | null;
                /** @description Named advertiser when reserved. */
                advertiser?: string | null;
                /** @enum {string|null} */
                listMode?: "rtb" | "whitelist_only" | null;
                storeScope?: string | null;
                quota?: number | null;
            }[];
            venue?: {
                openOohVenueType?: string;
                /** @enum {string} */
                orientation?: "landscape" | "portrait";
                loopLengthSec?: number;
            };
        };
        DeleteCheck: {
            canDelete: boolean;
            dependents: {
                /** @enum {string} */
                kind: "display" | "display_type_default" | "zone";
                name: string;
                /** @description e.g. store name or zone name */
                detail?: string;
            }[];
        };
        /** @description POC stand-in for the existing display type record (spec §8), including phExtensions. */
        DisplayType: {
            id: string;
            name: string;
            touchPoint: string;
            description?: string | null;
            displayCanvasSize: {
                width: number;
                height: number;
            };
            backgroundColor?: string;
            defaultPlaylistId?: string;
            /** @description null values mean inherit */
            playlistSettings: {
                [key: string]: unknown;
            };
            qrControl?: {
                [key: string]: unknown;
            };
            enabledFeatures?: {
                [key: string]: unknown;
            };
            multiZone?: {
                [key: string]: unknown;
            };
            phExtensions?: components["schemas"]["DisplayTypeExtensions"];
        };
        Playlist: {
            id: string;
            name: string;
            /** @description Display type id if auto-created */
            autoCreatedFor?: string | null;
            assignments: {
                displayTypeId: string;
                displayTypeName: string;
                zoneId?: string | null;
                zoneName?: string | null;
            }[];
        };
        /** @description POC stand-in for the existing campaign record (spec §8 additions included). Approval state is read from /admin/v1/approvals. */
        Campaign: {
            campaignId: string;
            name: string;
            /** @enum {string} */
            source: "hq" | "api" | "dsp";
            advertiserId?: string | null;
            advertiserName?: string | null;
            partnerId?: string | null;
            partnerName?: string | null;
            displayTypeId?: string | null;
            /** @enum {string|null} */
            pricingType?: "baseline" | "localised" | "personalised" | "interactive" | null;
            activation: {
                enabled: boolean;
            };
        };
        SellersJson: {
            contact_email?: string;
            /** @constant */
            version: "1.0";
            sellers: {
                seller_id: string;
                /** @constant */
                seller_type: "PUBLISHER";
                name: string;
                domain: string;
                /** @constant */
                is_confidential?: 0;
            }[];
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorised: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not allowed (e.g. non-admin on Advertisers) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found, or not visible to this caller */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description error.code = validation_failed; details lists each field */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description error.code = variable_not_permitted; details names each variable */
        VariableNotPermitted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description error.code = checks_failed; details lists each failed check with its reason */
        ChecksFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description error.code = not_approved | below_floor | advertiser_blocked | category_blocked | not_on_whitelist */
        NotEligible: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description error.code = conflict (e.g. version changed, already submitted, window sold, bidding not open or closed, live not allowed) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description error.code = has_dependents; details lists what depends on the item */
        HasDependents: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PositionId: string;
        CampaignId: string;
        PartnerId: string;
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listInventory: {
        parameters: {
            query?: {
                /** @description Scope to one of the partner's advertisers (applies their lists and floor multiplier). */
                advertiserId?: string;
                displayTypeId?: string;
                touchPoint?: "Digital Signage" | "Kiosk";
                /** @description Personalisation Hub store IDs (stores are managed by the platform). */
                storeIds?: string[];
                /** @description A store region from the platform's store records. */
                region?: string;
                from?: string;
                to?: string;
                status?: components["schemas"]["WindowStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Positions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Position"][];
                        nextCursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    getPosition: {
        parameters: {
            query?: {
                advertiserId?: string;
            };
            header?: never;
            path: {
                positionId: components["parameters"]["PositionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Position */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    getAvailability: {
        parameters: {
            query: {
                from: string;
                to: string;
                advertiserId?: string;
            };
            header?: never;
            path: {
                positionId: components["parameters"]["PositionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Windows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        positionId: string;
                        windows: components["schemas"]["PlayWindow"][];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    forecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    positionIds: string[];
                    /** Format: date */
                    from: string;
                    /** Format: date */
                    to: string;
                    advertiserId?: string;
                    rules?: components["schemas"]["TargetingRules"];
                };
            };
        };
        responses: {
            /** @description Forecast */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Projected VAC-d assumed views across the positions and dates. */
                        assumedViews: number;
                        /** @description ISO 4217 */
                        currency: string;
                        /** @description assumedViews / 1000 × effective floor CPM. */
                        estimatedCost: number;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            422: components["responses"]["VariableNotPermitted"];
        };
    };
    listTargetingAttributes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Variables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TargetingAttribute"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignStatus"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            422: components["responses"]["VariableNotPermitted"];
        };
    };
    uploadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description "baseline" or the targeted version id */
                    version: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded and checked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assetId: string;
                        checks: components["schemas"]["Check"][];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ChecksFailed"];
        };
    };
    submitCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignStatus"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ChecksFailed"];
        };
    };
    getCampaignStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignStatus"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    createReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["NotEligible"];
        };
    };
    getReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    getExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exchange settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exchange"];
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    saveExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeInput"];
            };
        };
        responses: {
            /** @description Saved; sellers.json republished when complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exchange"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdvertiserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvertiserSettings"];
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    saveAdvertiserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvertiserSettingsInput"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvertiserSettings"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAvailableInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AvailableInventoryRow"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    getSharedTargetingVariables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Variables with DSP access */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SharedVariable"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    saveVariableAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description variableKey → "all" or a list of partner ids ([] = none). */
                    access: {
                        [key: string]: components["schemas"]["VariableAccess"];
                    };
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SharedVariable"][];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            403: components["responses"]["Forbidden"];
        };
    };
    listPartners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured DSPs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Partner"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    addPartner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    provider: components["schemas"]["Provider"];
                };
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            409: components["responses"]["Conflict"];
        };
    };
    getPartner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: components["parameters"]["PartnerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DSP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    savePartner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: components["parameters"]["PartnerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartnerInput"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    connectPartner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: components["parameters"]["PartnerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result (status connected or error with the DSP's reason) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    disconnectPartner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: components["parameters"]["PartnerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected (mode reset to test) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdvertisers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Advertisers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        currency: string;
                        floorCpm: number;
                        items: components["schemas"]["Advertiser"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
            403: components["responses"]["Forbidden"];
        };
    };
    saveAdvertisers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description advertiserId → settings */
                    settings: {
                        [key: string]: components["schemas"]["AdvertiserSetting"];
                    };
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            403: components["responses"]["Forbidden"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApprovalStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approvals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        counts: {
                            draft: number;
                            awaiting_approval: number;
                            approved: number;
                            rejected: number;
                        };
                        items: components["schemas"]["Approval"][];
                        nextCursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    approveCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The version reviewed; rejected with 409 if it has changed. */
                    assetVersion: string;
                };
            };
        };
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            401: components["responses"]["Unauthorised"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    assetVersion: string;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    saveDisplayTypeExtensions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                displayTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayTypeExtensions"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayTypeExtensions"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    checkDisplayTypeDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                displayTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteCheck"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDisplayType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                displayTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["HasDependents"];
        };
    };
    checkPlaylistDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlistId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteCheck"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlistId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["HasDependents"];
        };
    };
    listDisplayTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Display types (existing fields plus phExtensions) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DisplayType"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    createDisplayType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayType"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayType"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
        };
    };
    getDisplayType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                displayTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Display type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayType"];
                };
            };
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    saveDisplayType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                displayTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayType"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayType"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    listPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Playlist"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    savePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlistId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
        };
    };
    listCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaigns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Campaign"][];
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    setCampaignActivation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorised"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["NotEligible"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        userId: string;
                        name: string;
                        /** @enum {string} */
                        role: "hq_admin" | "hq_user";
                    };
                };
            };
            401: components["responses"]["Unauthorised"];
        };
    };
    getSellersJson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description sellers.json */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellersJson"];
                };
            };
            /** @description Exchange settings incomplete; not published. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
