/* Turn E2E results files into the "E2E Test Results — <date>" project
   document (E2E Testing Strategy §3.4), in the format the hand-written ones
   used, and create it on the board.

     node scripts/report-e2e.mjs results/*.json             # create the document
     node scripts/report-e2e.mjs results/*.json --dry-run   # print it instead
     node scripts/report-e2e.mjs results/*.json --out results/report.md

   Inputs: vitest JSON reports of test/e2e (`npx vitest run test/e2e
   --reporter=json --outputFile=results/e2e.json`) and/or the journey
   runner's results (`npm run e2e:journey`). Needs BOARD_API_KEY to write;
   without it, it prints and exits 2 (unless --dry-run or --out). */
import { writeFileSync } from 'node:fs'
import { connect } from './lib/board.mjs'
import { byRun, merge } from './lib/results.mjs'

const args = process.argv.slice(2)
const flag = (n) => args.includes(n)
const value = (n) => (args.includes(n) ? args[args.indexOf(n) + 1] : undefined)
const files = args.filter((a) => !a.startsWith('--') && a !== value('--out'))
if (!files.length) { console.error('usage: node scripts/report-e2e.mjs <results.json...> [--dry-run] [--out file.md]'); process.exit(2) }

const r = merge(files)
const label = [...new Set(r.parts.map((p) => p.run))].join(' + ')
const name = `E2E Test Results — ${r.date} (${label})`
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ').slice(0, 300)
const mark = (c) => c.status === 'pass' ? 'pass' : c.status === 'fail' ? '**FAIL**' : c.status === 'known-gap' ? 'known gap' : 'skipped'

let md = `# ${name}\n\n`
md += `Generated by \`scripts/report-e2e.mjs\` from ${files.length} results file${files.length === 1 ? '' : 's'}; nothing here was hand-written.\n`
md += `Commit: ${r.commit ? `\`${r.commit}\`` : 'not recorded'} · Commands: ${[...new Set(r.parts.map((p) => `\`${p.command}\``))].join(', ')}\n\n`
md += `**Totals:** ${r.cases.length} cases — ${r.counts.pass} pass, ${r.counts.fail} fail, ${r.counts['known-gap']} known gap, ${r.counts.skipped} skipped.\n`
for (const p of r.parts) if (p.stopped) md += `\n**${p.run} stopped early:** ${p.stopped}\n`
md += `\n## Summary\n\n| Run | Cases | Pass | Fail | Known gap |\n|---|---|---|---|---|\n`
for (const [run, cs] of byRun(r.cases)) md += `| ${run} | ${cs.length} | ${cs.filter((c) => c.status === 'pass').length} | ${cs.filter((c) => c.status === 'fail').length} | ${cs.filter((c) => c.status === 'known-gap').length} |\n`
for (const [run, cs] of byRun(r.cases)) {
  md += `\n## ${run}\n\n| Case | Result | Detail |\n|---|---|---|\n`
  for (const c of cs) md += `| ${cell(c.title.startsWith(c.caseId) ? c.title : `${c.caseId} — ${c.title}`)} | ${mark(c)} | ${c.status === 'pass' ? '' : `expected: ${cell(c.expected)}; actual: ${cell(c.actual)}`} |\n`
}
const fails = r.cases.filter((c) => c.status === 'fail')
if (fails.length) {
  md += `\n## Failures\n\n`
  for (const c of fails) md += `- **${c.caseId}** (${c.run}) — ${c.title}\n  - expected: ${c.expected}\n  - actual: ${cell(c.actual)}\n  - repro: \`${c.repro}\`\n`
}

if (value('--out')) writeFileSync(value('--out'), md)
if (flag('--dry-run') || value('--out')) { console.log(flag('--dry-run') ? md : `Wrote ${value('--out')}`); process.exit(0) }
const board = await connect()
if (!board) { console.log(md); console.error('\nBOARD_API_KEY is not set: printed instead of creating the document (exit 2).'); process.exit(2) }
const docId = await board.createDocument({ name, contentMd: md })
console.log(`Created project document "${name}" (${docId}).`)
