/* GENERATED_BUILDS: a build output checked into the repo (the DSP
   integration's hosted prototype) is regenerated by a workflow, never by
   this script. Three things have to hold (22 Sep 2026, after three tickets
   failed testing on a link still serving the previous build):

   1. A change to the build's SOURCE names its workflow; a change to its
      OUTPUT, or to anything else, does not.
   2. The bundle's own API snapshot under apps/admin/public/demo/ counts as
      output even though it lives under a source prefix.
   3. A `git merge` conflict confined to the output is resolved by keeping
      the branch's copy, against a real disposable repo; a conflict that
      also touches a real file is left for a human. */
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFileSync } = require("node:child_process");

const { isGeneratedOutput, rebuildWorkflowsFor, tryAutoResolveGeneratedOutputConflict, conflictedPaths } = require("../scripts/run-backlog-automation.js");

// 1. Which paths mean "rebuild".
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/apps/admin/src/features/booking-schedule/BookingSchedulePage.tsx"]), ["dsp-prototype.yml"]);
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/packages/types/src/catalog.ts"]), ["dsp-prototype.yml"]);
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/apps/api/src/seed/seed.ts", "dsp-integration/docs/dsp-integration/REQUIREMENTS.md"]), ["dsp-prototype.yml"]);
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/package-lock.json"]), ["dsp-prototype.yml"]);
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/docs/dsp-integration/REQUIREMENTS.md"]), [], "docs alone do not change the bundle");
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/README.md", "backlog-tracker/public/js/app.js"]), []);
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/prototype/index.html", "dsp-integration/prototype/assets/index-abc.js"]), [], "the output itself never triggers a rebuild");
assert.deepStrictEqual(rebuildWorkflowsFor([]), []);
assert.deepStrictEqual(rebuildWorkflowsFor(undefined), []);
// A ticket's patch is one change: its docs and its source arrive together.
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/prototype/index.html", "dsp-integration/apps/admin/src/App.tsx"]), ["dsp-prototype.yml"]);

// 2. The snapshot under apps/ is output, not source.
assert.strictEqual(isGeneratedOutput("dsp-integration/apps/admin/public/demo/api-snapshot.json"), true);
assert.strictEqual(isGeneratedOutput("dsp-integration/apps/admin/public/demo/api-assets/x.svg"), true);
assert.strictEqual(isGeneratedOutput("dsp-integration/prototype/build-info.json"), true);
assert.strictEqual(isGeneratedOutput("dsp-integration/apps/admin/src/main.tsx"), false);
assert.strictEqual(isGeneratedOutput("dsp-integration/prototype-reference/thing.html"), false, "prefix match is on the directory, not the string");
assert.deepStrictEqual(rebuildWorkflowsFor(["dsp-integration/apps/admin/public/demo/api-snapshot.json"]), []);

// 3. The merge-conflict resolver, against a real repo.
function repo() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "generated-builds-"));
  const git = (...args) => execFileSync("git", args, { cwd: dir, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  const write = (rel, body) => {
    fs.mkdirSync(path.join(dir, path.dirname(rel)), { recursive: true });
    fs.writeFileSync(path.join(dir, rel), body);
  };
  git("init", "-q");
  git("checkout", "-q", "-b", "main");
  git("config", "user.email", "test@test.com");
  git("config", "user.name", "test");
  write("dsp-integration/prototype/index.html", "<script src=./assets/index-base.js>");
  write("dsp-integration/prototype/assets/index-base.js", "base");
  write("dsp-integration/prototype/build-info.json", '{"sourceStamp":"base"}');
  write("dsp-integration/apps/admin/src/App.tsx", "base");
  write("README.md", "base");
  git("add", "-A");
  git("commit", "-q", "-m", "base");
  return { dir, git, write };
}

// Both sides rebuilt: main after its own source change, the train after
// its ticket. index.html and build-info.json conflict; each side's hashed
// asset is an add on a different name (no conflict) and both deleted the
// old one (no conflict either).
{
  const { dir, git, write } = repo();
  git("checkout", "-q", "-b", "deploy/x");
  write("dsp-integration/apps/admin/src/App.tsx", "ticket");
  write("dsp-integration/prototype/index.html", "<script src=./assets/index-train.js>");
  write("dsp-integration/prototype/assets/index-train.js", "train");
  fs.rmSync(path.join(dir, "dsp-integration/prototype/assets/index-base.js"));
  write("dsp-integration/prototype/build-info.json", '{"sourceStamp":"train"}');
  git("add", "-A");
  git("commit", "-q", "-m", "ticket + rebuild on the train");

  git("checkout", "-q", "main");
  write("dsp-integration/apps/api/src/seed.ts", "hotfix on main");
  write("dsp-integration/prototype/index.html", "<script src=./assets/index-main.js>");
  write("dsp-integration/prototype/assets/index-main.js", "main");
  fs.rmSync(path.join(dir, "dsp-integration/prototype/assets/index-base.js"));
  write("dsp-integration/prototype/build-info.json", '{"sourceStamp":"main"}');
  git("add", "-A");
  git("commit", "-q", "-m", "hotfix + rebuild on main");

  git("checkout", "-q", "deploy/x");
  let failed = false;
  try { git("merge", "main", "--no-edit", "--quiet"); } catch { failed = true; }
  assert.ok(failed, "the two rebuilds must actually conflict for this test to mean anything");

  const prev = process.cwd();
  process.chdir(dir);
  try {
    const conflicted = conflictedPaths();
    assert.deepStrictEqual(conflicted.sort(), ["dsp-integration/prototype/build-info.json", "dsp-integration/prototype/index.html"]);
    const result = tryAutoResolveGeneratedOutputConflict(conflicted);
    assert.strictEqual(result.resolved, true, result.detail);
    assert.deepStrictEqual(conflictedPaths(), []);
    git("commit", "-q", "--no-edit");
    assert.strictEqual(fs.readFileSync(path.join(dir, "dsp-integration/prototype/index.html"), "utf8"), "<script src=./assets/index-train.js>", "the train's copy is kept");
    // The kept bundle was built before the merge, so its stamp is spoiled:
    // the next scheduled rebuild must regenerate it from the merged source
    // instead of finding a stamp that still matches.
    assert.match(JSON.parse(fs.readFileSync(path.join(dir, "dsp-integration/prototype/build-info.json"), "utf8")).sourceStamp, /^rebuild-after-merge:[0-9a-f]{7}$/);
    assert.strictEqual(fs.readFileSync(path.join(dir, "dsp-integration/apps/api/src/seed.ts"), "utf8"), "hotfix on main", "main's real change came through");
    assert.match(result.detail, /generated build output/);
    assert.strictEqual(git("rev-list", "--count", "HEAD"), "4", "base, ticket, hotfix, merge");
  } finally {
    process.chdir(prev);
  }
}

// A conflict that also touches a real file is not ours to resolve.
{
  const { dir, git, write } = repo();
  git("checkout", "-q", "-b", "deploy/y");
  write("README.md", "train");
  write("dsp-integration/prototype/index.html", "train");
  git("add", "-A");
  git("commit", "-q", "-m", "train");
  git("checkout", "-q", "main");
  write("README.md", "main");
  write("dsp-integration/prototype/index.html", "main");
  git("add", "-A");
  git("commit", "-q", "-m", "main");
  git("checkout", "-q", "deploy/y");
  try { git("merge", "main", "--no-edit", "--quiet"); } catch { /* expected */ }

  const prev = process.cwd();
  process.chdir(dir);
  try {
    const conflicted = conflictedPaths();
    assert.deepStrictEqual(conflicted.sort(), ["README.md", "dsp-integration/prototype/index.html"]);
    const result = tryAutoResolveGeneratedOutputConflict(conflicted);
    assert.strictEqual(result.resolved, false);
    assert.match(result.detail, /README\.md/);
    assert.deepStrictEqual(conflictedPaths().sort(), ["README.md", "dsp-integration/prototype/index.html"], "declining touches nothing");
  } finally {
    process.chdir(prev);
  }
}

// THE 25 SEP 2026 OUTAGE: both sides rebuilt a bundle that is nearly the
// same file under different hashed names, so git reports a rename/rename
// conflict — and for that shape it writes a two-way content merge WITH
// conflict markers into both renamed paths, recording that marker-laden
// blob as stages 2 and 3. `git checkout --ours` kept the markers, the merge
// committed them, and the hosted prototype threw `Unexpected token '==='`
// on load for twelve hours. The resolver must keep HEAD's real file, drop
// the other side's name, and never call a marker-carrying tree resolved.
{
  const { dir, git, write } = repo();
  const bundle = Array.from({ length: 300 }, (_, i) => `var v${i}=${i};function f${i}(){return v${i}*${i}+${i};}`).join("\n") + "\n";
  write("dsp-integration/prototype/assets/index-base.js", bundle);
  write("dsp-integration/prototype/index.html", "<script src=./assets/index-base.js>");
  git("add", "-A");
  git("commit", "-q", "-m", "a real-sized bundle");

  git("checkout", "-q", "-b", "deploy/z");
  const trainBundle = bundle.replace("var v1=1;", "var v1=1001;");
  write("dsp-integration/prototype/assets/index-train.js", trainBundle);
  fs.rmSync(path.join(dir, "dsp-integration/prototype/assets/index-base.js"));
  write("dsp-integration/prototype/index.html", "<script src=./assets/index-train.js>");
  write("dsp-integration/prototype/build-info.json", '{"sourceStamp":"train"}');
  git("add", "-A");
  git("commit", "-q", "-m", "rebuild on the train");

  git("checkout", "-q", "main");
  write("dsp-integration/prototype/assets/index-main.js", bundle.replace("var v2=2;", "var v2=2002;"));
  fs.rmSync(path.join(dir, "dsp-integration/prototype/assets/index-base.js"));
  write("dsp-integration/prototype/index.html", "<script src=./assets/index-main.js>");
  write("dsp-integration/prototype/build-info.json", '{"sourceStamp":"main"}');
  git("add", "-A");
  git("commit", "-q", "-m", "rebuild on main");

  git("checkout", "-q", "deploy/z");
  let mergeOutput = "";
  try { git("merge", "main", "--no-edit", "--quiet"); } catch (err) { mergeOutput = String(err.stdout || "") + String(err.stderr || ""); }
  assert.match(mergeOutput, /rename\/rename/, "the fixture must reproduce git's rename/rename shape, or this test proves nothing");
  assert.match(fs.readFileSync(path.join(dir, "dsp-integration/prototype/assets/index-train.js"), "utf8"), /^<{7,8} /m, "git wrote markers into the train's own renamed file");

  const prev = process.cwd();
  process.chdir(dir);
  try {
    const conflicted = conflictedPaths();
    assert.ok(conflicted.every(isGeneratedOutput), conflicted.join(", "));
    const result = tryAutoResolveGeneratedOutputConflict(conflicted);
    assert.strictEqual(result.resolved, true, result.detail);
    assert.deepStrictEqual(conflictedPaths(), []);
    git("commit", "-q", "--no-edit");
    assert.strictEqual(fs.readFileSync(path.join(dir, "dsp-integration/prototype/assets/index-train.js"), "utf8"), trainBundle, "the train's real file, byte for byte — no markers");
    assert.ok(!fs.existsSync(path.join(dir, "dsp-integration/prototype/assets/index-main.js")), "main's hashed asset is dropped");
    assert.ok(!fs.existsSync(path.join(dir, "dsp-integration/prototype/assets/index-base.js")), "the pre-rename path stays gone");
    assert.strictEqual(fs.readFileSync(path.join(dir, "dsp-integration/prototype/index.html"), "utf8"), "<script src=./assets/index-train.js>");
    const tracked = git("ls-files", "dsp-integration/prototype").split("\n");
    for (const f of tracked) {
      assert.ok(!/^(<{7,8}|={7,8}|>{7,8})( |$)/m.test(fs.readFileSync(path.join(dir, f), "utf8")), `${f} still carries a conflict marker`);
    }
    assert.match(JSON.parse(fs.readFileSync(path.join(dir, "dsp-integration/prototype/build-info.json"), "utf8")).sourceStamp, /^rebuild-after-merge:/);
  } finally {
    process.chdir(prev);
  }
}

assert.deepStrictEqual(tryAutoResolveGeneratedOutputConflict([]).resolved, false, "no conflict is not a resolved conflict");

console.log("generated-builds: all assertions passed");
