/* previewUrl must be pinned to a commit sha, never a branch name — githack
   caches a branch URL indefinitely, and a re-patch that kept reusing one
   could serve stale content under a tester's nose with no visible error
   (mIHraVz8fQXRe549UYD1, measured 25 Sep 2026 on this very project: a
   branch URL served the pre-change file 20 minutes after the commit that
   changed it landed, while the commit-sha URL for the same file was
   correct immediately — the same class of bug that cost the DSP project
   three false "Failed testing" rounds on 21-22 Sep). */
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const {
  isAutoGeneratedPreviewUrl,
  repointPreviewUrlRef,
  guessPreviewUrl,
} = require("../scripts/run-backlog-automation.js");

const REPO = "offline2online/rob_ph_demos";
const SHA_A = "7b09a4b7de59240db8c995f2393421fe7bdb41d4";
const SHA_B = "419bb79a690a7c332176dffe670b07b22c64eac8";
const BRANCH = "deploy/backlog-tracker-faqs";

// isAutoGeneratedPreviewUrl: only this pipeline's own two link shapes count
// as "ours to refresh" — anything else is a human's deliberate choice via
// the card's own "Set test link" flow and must never be silently
// overwritten just because a new commit landed on the train.
assert.strictEqual(isAutoGeneratedPreviewUrl(`https://rawcdn.githack.com/${REPO}/${SHA_A}/faq/index.html`), true);
assert.strictEqual(isAutoGeneratedPreviewUrl(`https://github.com/${REPO}/tree/${BRANCH}`), true);
assert.strictEqual(isAutoGeneratedPreviewUrl("https://example.com/some/custom/demo"), false, "a human's own link is never treated as ours");
assert.strictEqual(isAutoGeneratedPreviewUrl(null), false);
assert.strictEqual(isAutoGeneratedPreviewUrl(undefined), false);

// repointPreviewUrlRef: swaps only the ref segment, keeps the page path (or
// the whole tree link) intact, and never mangles a URL it doesn't own.
assert.strictEqual(
  repointPreviewUrlRef(`https://rawcdn.githack.com/${REPO}/${SHA_A}/faq/index.html`, SHA_B),
  `https://rawcdn.githack.com/${REPO}/${SHA_B}/faq/index.html`,
);
assert.strictEqual(
  repointPreviewUrlRef(`https://github.com/${REPO}/tree/${BRANCH}`, SHA_B),
  `https://github.com/${REPO}/tree/${SHA_B}`,
);
assert.strictEqual(repointPreviewUrlRef("https://example.com/demo", SHA_B), "https://example.com/demo");

// guessPreviewUrl: takes whatever ref string it's handed (a commit sha, same
// as a branch name before this fix) and never invents a branch of its own —
// the pin is entirely the caller's choice of what to pass as `ref`.
const root = fs.mkdtempSync(path.join(os.tmpdir(), "preview-url-pin-"));
const cwd = process.cwd();
process.chdir(root);
try {
  assert.strictEqual(
    guessPreviewUrl([{ path: "faq/index.html", content: "<html></html>" }], SHA_A, "https://fallback.example/"),
    `https://rawcdn.githack.com/${REPO}/${SHA_A}/faq/index.html`,
    "a changed page is pinned to the given ref, not a branch name",
  );
  assert.strictEqual(
    guessPreviewUrl([{ path: "lonely/scripts/tool.mjs", content: "// no page above me" }], SHA_A, "https://fallback.example/"),
    "https://fallback.example/",
    "no page anywhere above the change still falls back cleanly, whatever ref was passed",
  );
} finally {
  process.chdir(cwd);
  fs.rmSync(root, { recursive: true, force: true });
}

console.log("preview-url-pin: 9 assertions passed");
