-- Arrival order without rowid (Scope & Seam Reconciliation Review, 1 Oct
-- 2026, finding #19; ticket gAi2mkcm43uW6hrchOjh). Lists that must come back
-- in the order rows were written ordered by SQLite's hidden rowid, which
-- Postgres does not have. Each table gets an explicit seq: existing rows keep
-- their rowid order, and a new row takes the next number when it is inserted.
-- Queries order by seq, which is portable SQL. In Postgres the same column is
-- `seq BIGINT GENERATED BY DEFAULT AS IDENTITY`; the trigger below is the
-- SQLite adapter's way of filling it and does not travel. The insert and its
-- trigger are one statement, so two writers can never draw the same number.

ALTER TABLE display_types ADD COLUMN seq INTEGER;
UPDATE display_types SET seq = rowid;
CREATE INDEX display_types_seq ON display_types (seq);
CREATE TRIGGER display_types_seq_fill AFTER INSERT ON display_types WHEN NEW.seq IS NULL
BEGIN
  UPDATE display_types SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM display_types) WHERE id = NEW.id;
END;

ALTER TABLE playlists ADD COLUMN seq INTEGER;
UPDATE playlists SET seq = rowid;
CREATE INDEX playlists_seq ON playlists (seq);
CREATE TRIGGER playlists_seq_fill AFTER INSERT ON playlists WHEN NEW.seq IS NULL
BEGIN
  UPDATE playlists SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM playlists) WHERE id = NEW.id;
END;

ALTER TABLE displays ADD COLUMN seq INTEGER;
UPDATE displays SET seq = rowid;
CREATE INDEX displays_seq ON displays (seq);
CREATE TRIGGER displays_seq_fill AFTER INSERT ON displays WHEN NEW.seq IS NULL
BEGIN
  UPDATE displays SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM displays) WHERE id = NEW.id;
END;

ALTER TABLE partners ADD COLUMN seq INTEGER;
UPDATE partners SET seq = rowid;
CREATE INDEX partners_seq ON partners (seq);
CREATE TRIGGER partners_seq_fill AFTER INSERT ON partners WHEN NEW.seq IS NULL
BEGIN
  UPDATE partners SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM partners) WHERE id = NEW.id;
END;

ALTER TABLE buyers_lists ADD COLUMN seq INTEGER;
UPDATE buyers_lists SET seq = rowid;
CREATE INDEX buyers_lists_seq ON buyers_lists (seq);
CREATE TRIGGER buyers_lists_seq_fill AFTER INSERT ON buyers_lists WHEN NEW.seq IS NULL
BEGIN
  UPDATE buyers_lists SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM buyers_lists) WHERE id = NEW.id;
END;

ALTER TABLE reservations ADD COLUMN seq INTEGER;
UPDATE reservations SET seq = rowid;
CREATE INDEX reservations_seq ON reservations (seq);
CREATE TRIGGER reservations_seq_fill AFTER INSERT ON reservations WHEN NEW.seq IS NULL
BEGIN
  UPDATE reservations SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM reservations) WHERE id = NEW.id;
END;
