-- Arrival order without rowid, for the approval tables (host migration
-- 0037 does the same for the host's tables; see its header). In Postgres seq
-- is `BIGINT GENERATED BY DEFAULT AS IDENTITY` and the triggers do not travel.

ALTER TABLE campaign_approvals ADD COLUMN seq INTEGER;
UPDATE campaign_approvals SET seq = rowid;
CREATE INDEX campaign_approvals_seq ON campaign_approvals (seq);
CREATE TRIGGER campaign_approvals_seq_fill AFTER INSERT ON campaign_approvals WHEN NEW.seq IS NULL
BEGIN
  UPDATE campaign_approvals SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM campaign_approvals)
   WHERE campaign_id = NEW.campaign_id AND asset_version = NEW.asset_version;
END;

ALTER TABLE campaign_approval_audit ADD COLUMN seq INTEGER;
UPDATE campaign_approval_audit SET seq = rowid;
CREATE INDEX campaign_approval_audit_seq ON campaign_approval_audit (seq);
CREATE TRIGGER campaign_approval_audit_seq_fill AFTER INSERT ON campaign_approval_audit WHEN NEW.seq IS NULL
BEGIN
  UPDATE campaign_approval_audit SET seq = (SELECT COALESCE(MAX(seq), 0) + 1 FROM campaign_approval_audit) WHERE id = NEW.id;
END;
